---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mbuil.es
  resources:
  - egressgwk3s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mbuil.es
  resources:
  - egressgwk3s/finalizers
  verbs:
  - update
- apiGroups:
  - mbuil.es
  resources:
  - egressgwk3s/status
  verbs:
  - get
  - patch
  - update
